### ISSUE TITLE
CPAN Distribution is non GPL compliant

### ISSUE THREAD

**Issue by 2shortplanks** [rjbs/Dist-Zilla-Plugin-PodWeaver#10]
You've licensed this distribution under the GPL, but the distribution released to the CPAN doesn't include the original source code for the distribution (i.e. the un-weaved files that are on github)

**Comment by karenetheridge** [comment]
Side observation... I wonder if podweaver should print a warning at build time if the GPL licence is in use, to caution for exactly this case...

**Comment by rjbs** [comment]
Are you being serious?

Here are some reasons that I think this is bogus:

Both the source and the released form are under the GPL.  As the copyright holder, I am not bound to the licensing of the source material, and can release the derived work — the tarball's contents — under the GPL as a separate product.

The GPL does not require that the source is included.  It requires that it is *available*.  You can, instead of including the source, simply offer to make the source available at cost of distribution.  It is available, at a URL advertised in the release.  Admittedly, it is not phrased as "you can find the repository used to build this blah blah blah."
